contact_links:
  - name: ❔ Questions / Help
    url: https://github.com/rablonkk/discord.js-base-bot/discussions
    about: Please use GitHub Discussions for help and questions, do not start an issue.
  - name: 📃 Discord.js Guide
    url: https://discordjs.guide/
    about: The official guide for discord.js